apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: devops-case
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30150
  selector:
    app: mongodb 