name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # GHCR için gerekli

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_PUSH_PULL_TOKEN }}

      - name: Extract short commit SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/devops-case:${{ env.SHORT_SHA }}

      - name: Update Helm values.yaml with new image tag
        run: |
          sed -i "s/tag: .*/tag: ${{ env.SHORT_SHA }}/" chart/values.yaml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add chart/values.yaml
          git commit -m "ci: update image tag to ${{ env.SHORT_SHA }}" || echo "No changes to commit"
          git push